spring:
  application:
    name: CarRentalSys

  datasource:
    url: jdbc:postgresql://localhost:5432/carrentalsys
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
# JPA settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
# H2 Console (to view Database in browser
#  h2:
#    console:
#      enabled: true
